### ISSUE TITLE
Dependency issues for Jekyll on Windows

### ISSUE THREAD

**Issue by AdamCoscia** [gtvis/gtvis.github.io#13]
After installing Jekyll for Windows (https://jekyllrb.com/docs/installation/windows/) and running the commands from the root README (`npm install` and `bundle exec jekyll serve --livereload`), the current site's configuration produces this error:

https://stackoverflow.com/questions/30682575/unable-to-load-the-eventmachine-c-extension-to-use-the-pure-ruby-reactor

This was the solution that worked for my computer (Windows 10): https://stackoverflow.com/a/65547010

To fix it, I modified the Gemfile and added this line to the end:

`gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'`

I am not sure what the proper long-term solution would be here.

**Comment by arpitnarechania** [comment]
Adding 'eventmachine' did not impact installation on Mac and did not impact our CI-CD build pipeline to deploy Github Pages; closing the issue as the corresponding PR is merged.
