### ISSUE TITLE
Possible scraper bug for unique characters?

### ISSUE THREAD

**Issue by fredhohman** [gtvis/gtvis.github.io#2]
I noticed papers I co-authored with @cabreraalex didn't list his name in the authors list, and thought maybe the paper scraper doesn't capture unique characters, since I think Alex publishes under `Ángel`

**Comment by fredhohman** [comment]
I'll make sure to add him to the papers and submit a PR soon for a fix!

**Comment by gtvislab** [comment]
Can you confirm if the author list on any of those papers includes at least one of four core GT_Vis faculty? We have pulled in paper titles from DBLP but filtered them by our faculty.

**Comment by cabreraalex** [comment]
Aha that's funny I love it when my name breaks things. The paper is on the site, my name is just missing from it, if you `ctrl-f` for FairVis

**Comment by cabreraalex** [comment]
@arpitnarechania let me know if I can help!

**Comment by gtvislab** [comment]
Ok, got it now. While I will definitely check the script that did the one-time data entry, please send a PR with this (and other?) publication(s) updated.

**Comment by fredhohman** [comment]
I got it taken care of @cabreraalex! Will submit PR in the next day or two.

**Comment by cabreraalex** [comment]
Sweet, thanks so much for catching it as well!
